sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: JbGv37/VYvEsZ/uscoNUCZwQtHA/U9LyvgS/lgNvu3FiEJpOSSyuCm4Vjd0lZLO/YcKwZvbDf3i6ehsLx9PsV5gDs999Je9DJhIlCOCh3d70++Ndq0S8PrSkeH1oGQ0IEAK22ywdcKvieLplRRRdclX2zUEkKbkiIlItzJAGwAVf53imSCqWXdoreh4+/Cr1t8VEOfo2nSGsY9nm8Ew6dhnSKJ87esJ+2hZsudGc7+Ay/ufHwK6wALfyl0b0XFgI3aON8+gU3uHAafUb0d/57j++42TtkKEKjGkI1yPNGJfH84hScpx6xE/JK5NuGu45ygukMnY740mSBRKe5VaZ1dts2mj2xmHM1cONT+5PlzWERcP7UmDXq79YsPGSBebhk2uEoPUCAG95FFOg6TdhuwxoneZbZ2gjuQtXyDPCLPKFm0Sr9nbepY9Vy0mS1b+uam5WNhf58QFwJ4nPnuELPuRsEutwnfRcIPbNGVNUXwLnokAkdnYav8y4IEn8/P34s+Avva0fZVReBwUIXjaL+IKlWx2vchudAK+/Hd36Z1n0LdbI5JwbukKiAz6UMnHi6byAkevrqSiP7GPezinDC/cZ6z1M32hzPmGQIi3QOiVaV8zC00VWSCYmrvdSOUV116n8htpxcjdYN+BNFedNLtTELTQb4nFNSZMLZo9eip0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Country-of-the-Pointed-Firs_367
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy